edited run-backup for fedora

diff --git a/android/run-backup b/android/run-backup
--- a/android/run-backup
+++ b/android/run-backup
@@ -1,6 +1,23 @@
 #!/bin/sh
 
+LOCAL_DIR=/media/oneplus
+REMOTE_DIR=/volume1/oneplus
+
+if ! command -v adb-sync &>/dev/null; then
+  echo "Please install adb-sync"
+  exit 1
+fi
+
+if [[ ! -d "$LOCAL_DIR/sdcard" ]]; then
+  echo '######### MOUNT NFS #########'
+  pkexec mount -t nfs -o nfsvers=4,noexec 192.168.1.220:$REMOTE_DIR $LOCAL_DIR
+  if [[ $? != 0 ]]; then
+    echo "Cannot mount nfs"
+    exit 1
+  fi
+fi
+
 echo '######### ANDROID BACKUP #########'
-# -d delete | -e env | -j junk | -l list | -i device_id
-android-backup -dejl -i 29d3c130 $1
+# -d delete | -o out | -j junk | -f folders | -i device_id
+android-backup -dj -i 9969309f -o "$LOCAL_DIR/sdcard" -f "$LOCAL_DIR/backup_dir.txt" $1
 echo '############## END ##############'
